# 数据源配置
spring:
  datasource:
    # 默认数据源
    db:
      db-type: mysql
      # 数据库地址 rewriteBatchedStatements=true 开启mysql批量插入
      url: jdbc:mysql://106.14.119.3:3306/chen?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
      # 登录用户名
      username: root
      # 登录密码
      password: youqu
      # 驱动包
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据源平台
      platform: mysql
      # 使用druid连接池
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化连接池数量
      initial-size: 5
      # 最大连接池数量
      max-active: 50
      # 最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
      # max-idle: 10
      # 最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      min-idle: 5
      # 获取连接时最大等待时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 是否缓存preparedStatement，也就是PSCache
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0
      max-open-prepared-statements: -1
      # 保证安全性，申请连接的时候检测
      test-while-idle: true
      # 监控统计扩展插件
      filters: stat,wall,slf4j

    # 数据源2
    db2:
      db-type: mysql
      # 数据库地址 rewriteBatchedStatements=true 开启mysql批量插入
      url: jdbc:mysql://106.14.119.3:3306/chen2?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
      # 登录用户名
      username: root
      # 登录密码
      password: youqu
      # 驱动包
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据源平台
      platform: mysql
      # 阿里druid连接池
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化连接池数量
      initial-size: 5
      # 最大连接池数量
      max-active: 50
      # 最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
      # max-idle: 10
      # 最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      min-idle: 5
      # 获取连接时最大等待时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 是否缓存preparedStatement，也就是PSCache
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0
      max-open-prepared-statements: -1
      # 保证安全性，申请连接的时候检测
      test-while-idle: true
      # 监控统计扩展插件
      filters: stat,wall,slf4j