server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 10

spring:
  # 运行环境 dev:开发环境；test:测试环境；prod:生产环境
  profiles:
    active: dev
  jpa:
    # 数据库类型
    database: mysql
    # 数据库平台
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 显示sql
    show-sql: true
    hibernate:
      # 没有则创建，有则更新
      ddl-auto: update
    # 禁用视图
    open-in-view: false
  jackson:
    # 时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 时间区域
    time-zone: Asia/Chongqing
  http:
    converters:
      # 用于HTTP消息转换的首选JSON映射器
      preferred-json-mapper: gson
  gson:
    # 时间格式
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  # mybatis配置文件路径
  config-location: classpath:mybatis-config.xml
  # 扫描实体类所在包
  type-aliases-package: com.springBoot.entity
  # 编译后的mapper.xml扫描路径
  mapper-locations: classpath:*Mapper.xml

pagehelper:
  # 数据库方言
  helper-dialect: mysql
  # 分页的合理化数据
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true
  # 为了支持 startPage(Object params) 方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql

mapper:
  # 通用mapper类所在接口名称
  mappers: com.springBoot.commonMapper.MyMapper
  # 数据库
  identity: mysql