# 数据源配置
spring:
  # 数据源
  datasource:
    # 数据库地址
    url: jdbc:mysql://106.14.119.3:3306/chen?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    # 登录用户名
    username: root
    # 登录密码
    password: youqu
    # 驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源平台
    platform: mysql
    # 阿里druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 阿里连接池配置
    druid:
      # 初始化连接池数量
      initial-size: 3
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 50
      # 获取连接时最大等待时间
      max-wait: 60000
      # 是否缓存preparedStatement，也就是PSCache
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0
      max-open-prepared-statements: -1
      # 保证安全性，申请连接的时候检测
      test-while-idle: true
      # 监控统计扩展插件
      filters: stat,wall,slf4j