# 数据源配置
spring:
  # Atomikos配置
  jta:
    log-dir: logs/xa-logs
    atomikos:
      properties:
        enable-logging: true

  datasource:
    # 默认数据源
    db:
      # 唯一resource-name
      unique-resource-name: chen@120.132.116.16
      # 数据源className
      xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
      # 最小连接池数量
      min-pool-size: 2
      # 最大连接池数量
      max-pool-size: 10
      # 连接检查
      # test-query: select 1 from dual
      # xa属性配置
      xa-properties:
        # druid可视化界面中显示的数据源名称
        name: chen@120.132.116.16
        url: jdbc:mysql://120.132.116.16:3306/chen?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&autoReconnect=true
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
        # druid连接池初始化连接数
        initialSize: 2
        # 最小空闲值
        minIdle: 2
        # 最大连接池数量
        maxActive: 10
        # 获取连接时最大等待时间 单位毫秒
        maxWait: 60000
        # 连接在连接池中最小生存的时间 毫秒
        minEvictableIdleTimeMillis: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接 单位毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 是否缓存preparedStatement，也就是PSCache mysql建议false
        poolPreparedStatements: false
        # 要启用PSCache，必须配置大于0 (建议100)
        maxOpenPreparedStatements: -1
        # 空闲时检测，保证安全性，配合timeBetweenEvictionRunsMillis
        testWhileIdle: true
        # 获取连接时检测，执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnBorrow: false
        # 连接放回连接池时检测，执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnReturn: false
        # 用来检测连接是否有效的sql，要求是一个查询语句.如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
        validationQuery: select 1 from dual
        # 用来检测连接是否有效的sql的超时时间 毫秒
        validationQueryTimeout: 10000
        # 监控统计扩展插件
        filters: stat,slf4j,wall

    # 数据源2
    db2:
      # 唯一resource-name
      unique-resource-name: chen2@120.132.116.16
      # 数据源className
      xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
      # 最小连接池数量
      min-pool-size: 2
      # 最大连接池数量
      max-pool-size: 10
      # 连接检查
      # test-query: select 1 from dual
      # xa属性配置
      xa-properties:
        # druid可视化界面中显示的数据源名称
        name: chen2@120.132.116.16
        url: jdbc:mysql://120.132.116.16:3306/chen2?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&autoReconnect=true
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
        # druid连接池初始化连接数
        initialSize: 2
        # 最小空闲值
        minIdle: 2
        # 最大连接池数量
        maxActive: 10
        # 获取连接时最大等待时间 单位毫秒
        maxWait: 60000
        # 连接在连接池中最小生存的时间 毫秒
        minEvictableIdleTimeMillis: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接 单位毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 是否缓存preparedStatement，也就是PSCache mysql建议false
        poolPreparedStatements: false
        # 要启用PSCache，必须配置大于0 (建议100)
        maxOpenPreparedStatements: -1
        # 空闲时检测，保证安全性，配合timeBetweenEvictionRunsMillis
        testWhileIdle: true
        # 获取连接时检测，执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnBorrow: false
        # 连接放回连接池时检测，执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnReturn: false
        # 用来检测连接是否有效的sql，要求是一个查询语句.如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
        validationQuery: select 1 from dual
        # 用来检测连接是否有效的sql的超时时间 毫秒
        validationQueryTimeout: 10000
        # 监控统计扩展插件
        filters: stat,slf4j,wall

    # druid配置
    druid:
      # StatViewServlet配置
      # 开启页面访问展示  路径 /druid
      stat-view-servlet:
        enabled: true
        # 根据配置中的url-pattern来访问内置监控页面，如果是以下的配置，内置监控页面的首页是/druid/index.html
        url-pattern: /druid/*
        # 允许清空数据
        reset-enable: true
        # druid登录用户名
        login-username: druid
        # druid 登录发密码
        login-password: druid
        # 如果allow没有配置或者为空，则允许所有访问;deny优先于allow，如果不在deny列表中，就算在allow列表中，也会被拒绝
        allow:
        # deny: 127.0.0.1

      # StatFilter配置
      web-stat-filter:
        # 是否启用StatFilter 默认开启
        enabled: true
        # url-pattern:
        # profile-enable:
        # principal-cookie-name:
        # principal-session-name:
        # 过滤访问,需要排除一些不必要的url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        # session统计功能
        session-stat-enable: true
        # session存储个数，缺省sessionStatMaxCount是1000个
        session-stat-max-count: 1000

      # filter配置
      filter:
        stat:
          # 开启filter
          enabled: true
          # 合并SQL
          merge-sql: true
          # 慢SQL记录
          log-slow-sql: true
          # 多于这个时间的SQL执行时间为慢SQL
          slow-sql-millis: 5000